### ISSUE TITLE
Address template feedback

### ISSUE THREAD

**Issue by awunderground** [UI-Research/gates-mobility-metrics-pages#161]
## Overall

- [x] Give the page/ your H1 a meaningful title by giving some insight into what this page will show. Perhaps an H1 like "Mobility metrics for city name, state name" could set the stage for what we are about to read? Maybe that’s not needed because at a higher level context is given.
- [x] The h1 is closer to the logo than the content, I would suggest either splitting the difference or making the h1 closer to the h2 than the logo.

 
## H1

- [x] increase font size to 36px
- [x] change font weight to 700
- [x] change color to #000000

## H2

- [x] don't use blue unless it's a link. Change color to #353535
- [x] change font weight to 700
- [x] try a bottom border 1px solid #d2d2d2 with 12px of padding below the h tag for a visual signal of grouping

## H3

- [x] change font weight to 700

 

- [x] H1, H2, H3 should all be 700 font weight as they are important enough to have space in your navigation
- [x] change all the text except h1 and links to #353535
- [ ] The em content directly below the H3 should be increased to 18px, and the link should be 700 font weight and #1696d2
- [x] links should use Urban's blue #1696d2
- [ ] .nav li a increase to 18px and font weight 700
- [ ] remove .nav-tabs bottom border and to get that line below instead remove 12px of padding on .tabbed-pane
- [x] Increase the table headers from 14 to 16px and increase the table cells from 12 to 14px

## Navigation/TOC

- [ ] Could the nav start opened at the point where we can see all the parent elements and not just the grandparent element/city name?
- [x] Remove the border around the TOC
